
package wcf;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ArgumentException", targetNamespace = "http://schemas.datacontract.org/2004/07/System")
public class IBrokerServiceRetrieveDataArgumentExceptionFaultFaultMessage
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ArgumentException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public IBrokerServiceRetrieveDataArgumentExceptionFaultFaultMessage(String message, ArgumentException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public IBrokerServiceRetrieveDataArgumentExceptionFaultFaultMessage(String message, ArgumentException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: wcf.ArgumentException
     */
    public ArgumentException getFaultInfo() {
        return faultInfo;
    }

}
